### ISSUE TITLE
Can not launch Android Studio after upgrading to 4.1.1.0

### ISSUE THREAD

**Issue by zhopon** [snapcrafters/android-studio#82]
When launching Android Studio crashes with the following error:

> 2020-11-15 10:30:47,737 [    180]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManagerCore.loadDescriptors()[Lcom/intellij/ide/plugins/IdeaPluginDescriptorImpl; 
> java.lang.NoSuchMethodError: com.intellij.ide.plugins.PluginManagerCore.loadDescriptors()[Lcom/intellij/ide/plugins/IdeaPluginDescriptorImpl;
> 	at com.a.a.b.b.ar.a(ar.java:121)
> 	at com.a.a.b.b.ar.a(ar.java:71)
> 	at com.intellij.idea.MainImpl.start(MainImpl.java:19)
> 	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
> 	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
> 	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
> 	at java.lang.Thread.run(Thread.java:748)
> 2020-11-15 10:30:47,739 [    182]  ERROR - llij.ide.plugins.PluginManager - Android Studio 4.1.1  Build #AI-201.8743.12.41.6953283 
> 2020-11-15 10:30:47,739 [    182]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_242-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
> 2020-11-15 10:30:47,739 [    182]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
> 
> Start Failed: Internal error. Please refer to https://code.google.com/p/android/issues
> 
> java.lang.NoSuchMethodError: com.intellij.ide.plugins.PluginManagerCore.loadDescriptors()[Lcom/intellij/ide/plugins/IdeaPluginDescriptorImpl;
> 	at com.a.a.b.b.ar.a(ar.java:121)
> 	at com.a.a.b.b.ar.a(ar.java:71)
> 	at com.intellij.idea.MainImpl.start(MainImpl.java:19)
> 	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
> 	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
> 	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> -----
> JRE 1.8.0_242-release-1644-b3-6222593 amd64 by JetBrains s.r.o
> /snap/android-studio/97/android-studio/jre/jre
>

**Comment by zhopon** [comment]
Fixed by removing ~/.local/share/Google/AndroidStudio4.1
